CUDA_VISIBLE_DEVICES=0,1 accelerate launch --num_processes 4 --main_process_port 5812 train_clm.py \
--output_dir runs/debug_gpt2_ddp \
--data_dir ../data/cuad_contracts \
--model_path gpt2 \
--dtype bf16 \
--lr 1e-4 \
--total_bs 128 \
--device_bs 2 \
--max_steps 1000 \
--log_steps 5 \
--save_steps 100 \
--save_total_limit 5 \
--max_length 1024
